export const THEMES = [
  {
    name: "light",
    label: "Light",
    colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"],
  },
  {
    name: "dark",
    label: "Dark",
    colors: ["#1f2937", "#8b5cf6", "#ec4899", "#1a202c"],
  },
  {
    name: "bumblebee",
    label: "Bumblebee",
    colors: ["#ffffff", "#f8e36f", "#f0d50c", "#1c1917"],
  },
  {
    name: "cyberpunk",
    label: "Cyberpunk",
    colors: ["#ffee00", "#ff7598", "#75d1f0", "#1a103d"],
  },
  {
    name: "valentine",
    label: "Valentine",
    colors: ["#f0d6e8", "#e96d7b", "#a991f7", "#37243c"],
  },
];

export const NATIONALITIES = [
  "American",
  "British",
  "Canadian",
  "Australian",
  "German",
  "French", 
  "Spanish",
  "Italian",
  "Japanese",
  "Korean",
  "Chinese",
  "Indian",
  "Brazilian",
  "Mexican",
  "Russian",
  "Turkish",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Swiss",
  "Austrian",
  "Belgian",
  "Portuguese",
  "Greek",
  "Polish",
  "Czech",
  "Hungarian",
  "Romanian",
  "Bulgarian",
  "Croatian",
  "Serbian",
  "Ukrainian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Slovenian",
  "Slovakian",
  "Maltese",
  "Cypriot",
  "Irish",
  "Icelandic",
  "Luxembourg",
  "Monégasque",
  "Liechtensteiner",
  "San Marinese",
  "Andorran",
  "Vatican",
];

// CHANGED: Replace LANGUAGE_TO_FLAG with NATIONALITY_TO_FLAG
export const NATIONALITY_TO_FLAG = {
  american: "us",
  british: "gb", 
  canadian: "ca",
  australian: "au",
  german: "de",
  french: "fr",
  spanish: "es",
  italian: "it",
  japanese: "jp",
  korean: "kr",
  chinese: "cn",
  indian: "in",
  brazilian: "br",
  mexican: "mx",
  russian: "ru",
  turkish: "tr",
  dutch: "nl",
  swedish: "se",
  norwegian: "no",
  danish: "dk",
  finnish: "fi",
  swiss: "ch",
  austrian: "at",
  belgian: "be",
  portuguese: "pt",
  greek: "gr",
  polish: "pl",
  czech: "cz",
  hungarian: "hu",
  romanian: "ro",
  bulgarian: "bg",
  croatian: "hr",
  serbian: "rs",
  ukrainian: "ua",
  lithuanian: "lt",
  latvian: "lv",
  estonian: "ee",
  slovenian: "si",
  slovakian: "sk",
  maltese: "mt",
  cypriot: "cy",
  irish: "ie",
  icelandic: "is",
  luxembourg: "lu",
};